Trying to fix broken github pipelines

diff --git a/.github/workflows/qa-setup-pipeline.yml b/.github/workflows/qa-setup-pipeline.yml
--- a/.github/workflows/qa-setup-pipeline.yml
+++ b/.github/workflows/qa-setup-pipeline.yml
@@ -26,8 +26,8 @@ env:
   TF_VAR_availability_zones: '["us-east-1a", "us-east-1b"]'
   TF_VAR_ecs_task_cpu: 256
   TF_VAR_ecs_task_memory: 512
-  TF_VAR_dockerfile_path: GroundUp.api/Dockerfile
-  TF_VAR_dockerfile_ef_path: GroundUp.api/Dockerfile.ef
+  TF_VAR_dockerfile_path: GroundUp.Api/Dockerfile
+  TF_VAR_dockerfile_ef_path: GroundUp.Api/Dockerfile.ef
   TF_VAR_backend_bucket: rsbst23-ground-up-qa-terraform-state
   TF_VAR_backend_key: terraform.state
   TF_VAR_backend_region: "us-east-1"
@@ -199,7 +199,7 @@ jobs:
           ECR_REPOSITORY: ${{ env.TF_VAR_ecr_repository_name }}-ef-migrations
         run: |          
           echo "Building EF Migrations Docker image..."
-          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -f GroundUp.api/Dockerfile.ef . || (echo "EF Docker Build Failed!" && exit 1)
+          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -f GroundUp.Api/Dockerfile.ef . || (echo "EF Docker Build Failed!" && exit 1)
 
           echo "Listing Docker images to verify build success:"
           docker images | grep "$ECR_REGISTRY/$ECR_REPOSITORY"
